// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCEES3viTfyFRzSDUcrT43MLR2H698bww',
    appId: '1:233341246796:web:ac7d25d8d65292b84f43e9',
    messagingSenderId: '233341246796',
    projectId: 'sellers-app-94f55',
    authDomain: 'sellers-app-94f55.firebaseapp.com',
    storageBucket: 'sellers-app-94f55.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGUnR_i9ohPkpZrjCsxDNV-B4LFChvTw8',
    appId: '1:233341246796:android:e1c743c13235ff424f43e9',
    messagingSenderId: '233341246796',
    projectId: 'sellers-app-94f55',
    storageBucket: 'sellers-app-94f55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_1Rp_9b5LHaqh_ZVC4NLCvk3BfaOJnY0',
    appId: '1:233341246796:ios:b4ed6d08ea1625184f43e9',
    messagingSenderId: '233341246796',
    projectId: 'sellers-app-94f55',
    storageBucket: 'sellers-app-94f55.appspot.com',
    iosBundleId: 'com.example.foodPandaUberEatsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_1Rp_9b5LHaqh_ZVC4NLCvk3BfaOJnY0',
    appId: '1:233341246796:ios:127af51dbf10a87c4f43e9',
    messagingSenderId: '233341246796',
    projectId: 'sellers-app-94f55',
    storageBucket: 'sellers-app-94f55.appspot.com',
    iosBundleId: 'com.example.foodPandaUberEatsApp.RunnerTests',
  );
}
